/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.kafka.streams.schemas;
/** The severity level of the event */
@org.apache.avro.specific.AvroGenerated
public enum Severity implements org.apache.avro.generic.GenericEnumSymbol<Severity> {
  EMERG, ALERT, CRIT, ERR, WARNING, NOTICE, INFO, DEBUG  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Severity\",\"namespace\":\"io.confluent.kafka.streams.schemas\",\"doc\":\"The severity level of the event\",\"symbols\":[\"EMERG\",\"ALERT\",\"CRIT\",\"ERR\",\"WARNING\",\"NOTICE\",\"INFO\",\"DEBUG\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
